"""Seed database package — exports seed function and constants."""

from db.seed.constants import (
    KEY_CHEMISTRY_TUTOR,
    KEY_ENGLISH_TUTOR,
    KEY_MATH_1,
    KEY_MATH_2,
    KEY_MATH_3,
    KEY_MATH_4,
    KEY_MATH_5,
    KEY_PHYSICS_TUTOR,
    KEY_RUSSIAN_TUTOR,
    KEY_STUDENT_NEW1,
    KEY_STUDENT_NEW2,
    KEY_STUDENT_OLGA,
    KEY_STUDENT_TATIANA,
    KEY_SUD_STUDENT,
    NOW,
    SUBJ_CHEMISTRY,
    SUBJ_ENGLISH,
    SUBJ_HISTORY,
    SUBJ_MATH,
    SUBJ_PHYSICS,
    SUBJ_RUSSIAN,
    TAG_EGE,
    TAG_EXPERIENCED,
    TAG_INDIVIDUAL,
    TAG_INTERACTIVE,
    TAG_PATIENT,
    TAG_REMOTE,
    TAG_STRICT,
    TAG_YOUNG,
    TEST_LIB_1_ID,
    TEST_LIB_2_ID,
    TEST_LIB_3_ID,
)
from db.seed.main import _table_empty, seed_database

__all__ = [
    "seed_database",
    "_table_empty",
    # Keys for user_uuid dict (from Keycloak)
    "KEY_RUSSIAN_TUTOR",
    "KEY_SUD_STUDENT",
    "KEY_MATH_1",
    "KEY_MATH_2",
    "KEY_MATH_3",
    "KEY_MATH_4",
    "KEY_MATH_5",
    "KEY_CHEMISTRY_TUTOR",
    "KEY_PHYSICS_TUTOR",
    "KEY_ENGLISH_TUTOR",
    "KEY_STUDENT_OLGA",
    "KEY_STUDENT_TATIANA",
    "KEY_STUDENT_NEW1",
    "KEY_STUDENT_NEW2",
    # Static constants
    "SUBJ_MATH",
    "SUBJ_PHYSICS",
    "SUBJ_RUSSIAN",
    "SUBJ_ENGLISH",
    "SUBJ_CHEMISTRY",
    "SUBJ_HISTORY",
    "TAG_PATIENT",
    "TAG_INTERACTIVE",
    "TAG_STRICT",
    "TAG_EXPERIENCED",
    "TAG_YOUNG",
    "TAG_REMOTE",
    "TAG_INDIVIDUAL",
    "TAG_EGE",
    "TEST_LIB_1_ID",
    "TEST_LIB_2_ID",
    "TEST_LIB_3_ID",
    "NOW",
]
